-- Schema do domínio hospitalar. Compatível com PostgreSQL e com H2 em modo PostgreSQL:
-- identidade via GENERATED BY DEFAULT AS IDENTITY, sem tipos exclusivos (TEXT, CHAR) nem índices parciais.

CREATE TABLE paciente (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150) NOT NULL,
    telefone        VARCHAR(20),
    email           VARCHAR(150),
    ativo           BOOLEAN      NOT NULL DEFAULT TRUE,
    cpf             VARCHAR(11)  NOT NULL,
    data_nascimento DATE         NOT NULL,
    logradouro      VARCHAR(150),
    numero          VARCHAR(10),
    complemento     VARCHAR(100),
    bairro          VARCHAR(100),
    cidade          VARCHAR(100),
    uf              VARCHAR(2),
    cep             VARCHAR(8),
    CONSTRAINT uk_paciente_cpf UNIQUE (cpf)
);

CREATE TABLE profissional_saude (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                  VARCHAR(150) NOT NULL,
    telefone              VARCHAR(20),
    email                 VARCHAR(150),
    ativo                 BOOLEAN      NOT NULL DEFAULT TRUE,
    registro_profissional VARCHAR(30)  NOT NULL,
    especialidade         VARCHAR(100) NOT NULL,
    CONSTRAINT uk_profissional_saude_registro UNIQUE (registro_profissional)
);

CREATE TABLE quarto (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero            VARCHAR(10) NOT NULL,
    andar             INTEGER     NOT NULL,
    capacidade_maxima INTEGER     NOT NULL,
    ocupacao_atual    INTEGER     NOT NULL DEFAULT 0,
    versao            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_quarto_numero UNIQUE (numero),
    CONSTRAINT ck_quarto_capacidade CHECK (capacidade_maxima > 0),
    CONSTRAINT ck_quarto_ocupacao CHECK (ocupacao_atual >= 0 AND ocupacao_atual <= capacidade_maxima)
);

CREATE TABLE consulta (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id                 BIGINT        NOT NULL,
    profissional_responsavel_id BIGINT        NOT NULL,
    observacoes                 VARCHAR(1000),
    data                        DATE          NOT NULL,
    horario                     TIME          NOT NULL,
    motivo                      VARCHAR(500)  NOT NULL,
    status                      VARCHAR(20)   NOT NULL,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT fk_consulta_profissional FOREIGN KEY (profissional_responsavel_id) REFERENCES profissional_saude (id),
    CONSTRAINT ck_consulta_status CHECK (status IN ('AGENDADA', 'REALIZADA', 'CANCELADA'))
);

-- Verificação de conflito de horários (por profissional e por paciente em uma data) e histórico do paciente.
CREATE INDEX idx_consulta_profissional_data ON consulta (profissional_responsavel_id, data);
CREATE INDEX idx_consulta_paciente_data ON consulta (paciente_id, data);

CREATE TABLE internacao (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id                 BIGINT        NOT NULL,
    profissional_responsavel_id BIGINT        NOT NULL,
    observacoes                 VARCHAR(1000),
    quarto_id                   BIGINT        NOT NULL,
    data_entrada                DATE          NOT NULL,
    data_prevista_alta          DATE          NOT NULL,
    data_efetiva_alta           DATE,
    CONSTRAINT fk_internacao_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT fk_internacao_profissional FOREIGN KEY (profissional_responsavel_id) REFERENCES profissional_saude (id),
    CONSTRAINT fk_internacao_quarto FOREIGN KEY (quarto_id) REFERENCES quarto (id),
    CONSTRAINT ck_internacao_alta_prevista CHECK (data_prevista_alta >= data_entrada),
    CONSTRAINT ck_internacao_alta_efetiva CHECK (data_efetiva_alta IS NULL OR data_efetiva_alta >= data_entrada)
);

CREATE INDEX idx_internacao_paciente ON internacao (paciente_id);
CREATE INDEX idx_internacao_profissional ON internacao (profissional_responsavel_id);
CREATE INDEX idx_internacao_quarto ON internacao (quarto_id);
